//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CdeGastosApp.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleGasto
    {
        public int Id { get; set; }
        public int GastoId { get; set; }
        public int ActividadInsumoId { get; set; }
        public double CantidadGasto { get; set; }
        public decimal CostoGasto { get; set; }
    
        public virtual Gasto Gasto { get; set; }
        public virtual ActividadInsumo ActividadInsumo { get; set; }
    }
}
