#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("CdeGastosAndroidApp.Resource", IsApplication=true)]

namespace CdeGastosAndroidApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050007
			public const int btnIniciarSesion = 2131034119;
			
			// aapt resource value: 0x7f05000e
			public const int button1 = 2131034126;
			
			// aapt resource value: 0x7f050001
			public const int lblMensaje = 2131034113;
			
			// aapt resource value: 0x7f050008
			public const int lblRegistrarUsuario = 2131034120;
			
			// aapt resource value: 0x7f050002
			public const int space1 = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int textView2 = 2131034115;
			
			// aapt resource value: 0x7f050005
			public const int textView3 = 2131034117;
			
			// aapt resource value: 0x7f050000
			public const int textView5 = 2131034112;
			
			// aapt resource value: 0x7f05000a
			public const int txtApellidos = 2131034122;
			
			// aapt resource value: 0x7f05000d
			public const int txtConfirmarContrasenia = 2131034125;
			
			// aapt resource value: 0x7f050006
			public const int txtContrasenia = 2131034118;
			
			// aapt resource value: 0x7f05000c
			public const int txtEmail = 2131034124;
			
			// aapt resource value: 0x7f05000b
			public const int txtNombreUsuario = 2131034123;
			
			// aapt resource value: 0x7f050009
			public const int txtNombres = 2131034121;
			
			// aapt resource value: 0x7f050004
			public const int txtUsuario = 2131034116;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int RegistrarUsuario = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int ApplicationName = 2130968576;
			
			// aapt resource value: 0x7f040005
			public const int btnIniciarSesion = 2130968581;
			
			// aapt resource value: 0x7f04000c
			public const int btnRegistrarUsuario = 2130968588;
			
			// aapt resource value: 0x7f040008
			public const int lblApellidos = 2130968584;
			
			// aapt resource value: 0x7f04000b
			public const int lblConfirmarContrasenia = 2130968587;
			
			// aapt resource value: 0x7f040004
			public const int lblContrasenia = 2130968580;
			
			// aapt resource value: 0x7f040009
			public const int lblEmail = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int lblNombreUsuario = 2130968586;
			
			// aapt resource value: 0x7f040007
			public const int lblNombres = 2130968583;
			
			// aapt resource value: 0x7f040001
			public const int lblTituloInicioSesion = 2130968577;
			
			// aapt resource value: 0x7f040006
			public const int lblTituloRegistrarUsuario = 2130968582;
			
			// aapt resource value: 0x7f040002
			public const int lblTituloRegistrarse = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int lblUsuario = 2130968579;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
